#+DATE: [2019-04-06 Sat 08:31]
#+TITLE: What is the Expectation Maximization (EM) Algorithm?
#+AUTHOR: Kazuki Yoshida
#+OPTIONS: toc:nil
#+OPTIONS: ^:{}
# ############################################################################ #

# * Introduction # (Do no use a header here)
# M-x org-html-export-to-html-citeproc to check locally.
# M-x my-wp-directly-post-as-draft-citeproc to upload as a draft.

We are often faced with the issues of incomplete data. This can include typical missing data problems and also latent variables, /i.e./ some underlying state that remains unobserved. Using an example from Do and Batzoglou cite:doWhatExpectationMaximization2008, we will review the Expectation-Maximization (EM) algorithm.

* Complete-Data Example

** A Coin-Flipping Experiment
- Two coins $A$ (0) and $B$ (1) with unknown head probabilities $(\theta_{0},\theta_{1})$
- Repeat 5 times
  1. Randomly pick either coin with equal probability and record
  2. Toss 10 times and record the number of heads

** A Coin-Flipping Experiment (More Formal)
- Two coins $A$ (0) and $B$ (1) with unknown head probabilities $(\theta_{0},\theta_{1})$
- For $i = 1, \dots, 5$
  1. Draw $Z_{i} \sim \text{Bernoulli}(p = 0.5), Z_{i} \in \left\{ 0,1 \right\}$
  2. Draw $X_{i} | Z_{i} \sim \text{Binomial}(n = 10, p = \theta_{Z_{i}}), X_{i} \in \left\{ 0, \dots, 10 \right\}$
| Index |    Coin |   Heads |
|   $i$ | $Z_{i}$ | $X_{i}$ |
|-------+---------+---------|
|     1 |       1 |       5 |
|     2 |       0 |       9 |
|     3 |       0 |       8 |
|     4 |       1 |       4 |
|     5 |       0 |       7 |
- Note that you only need the number of heads ([[https://www.statisticshowto.datasciencecentral.com/sufficient-statistic/][sufficient statistic]]), not the entire sequence.

* Part 2

Wyss et al. cite:WyssUsingTimeDependentPropensity2018 extensively examined the issue previously suggested cite:HernanHazardsHazardRatios2010.

* Code example
# Only png can be handled. Do not use pdf.
#+HEADER: :width 350 :height 300
#+BEGIN_SRC R :session *R* :results output graphics :file ./source/figure.png :exports both
library(ggplot2)
ggplot(data = diamonds, mapping = aes(x = carat, y = price, color = color)) +
    geom_point() +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
          legend.key = element_blank(),
          plot.title = element_text(hjust = 0.5),
          strip.background = element_blank())
#+END_SRC


* Conclusion

In conclusion, we examined a better way to export from an org-mode document to datascienceplus.com.


* Bibliography
# Following lines must be left-aligned without preceding spaces.
bibliographystyle:unsrt
bibliography:~/.emacs.d/misc/zotero.bib
