---
title: "Bayesian Ideas and Data Analysis in Stan: Log-normal AFT"
author: "Kazuki Yoshida"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: html_document
---

```{r, message = FALSE, tidy = FALSE, echo = F}
## knitr configuration: http://yihui.name/knitr/options#chunk_options
library(knitr)
showMessage <- FALSE
showWarning <- TRUE
set_alias(w = "fig.width", h = "fig.height", res = "results")
opts_chunk$set(comment = "##", error= TRUE, warning = showWarning, message = showMessage,
               tidy = FALSE, cache = F, echo = T,
               fig.width = 7, fig.height = 7, dev.args = list(family = "sans"))
## for rgl
## knit_hooks$set(rgl = hook_rgl, webgl = hook_webgl)
## for animation
opts_knit$set(animation.fun = hook_ffmpeg_html)

## R configuration
options(width = 116, scipen = 5)

## Configure parallelization
## Parallel backend for foreach (also loads foreach and parallel; includes doMC)
library(doParallel)
## Reproducible parallelization
library(doRNG)
## Detect core count (Do not use on clusters)
n_cores <- parallel::detectCores()
## Used by parallel::mclapply() as default
options(mc.cores = n_cores)
## Used by doParallel as default
options(cores = n_cores)
## Register doParallel as the parallel backend with foreach
## http://stackoverflow.com/questions/28989855/the-difference-between-domc-and-doparallel-in-r
doParallel::registerDoParallel(cores = n_cores)
## Report multicore use
## cat("### Using", foreach::getDoParWorkers(), "cores\n")
## cat("### Using", foreach::getDoParName(), "as backend\n")
```


## References
- [Stan for survival models](https://discourse.mc-stan.org/t/stan-for-survival-models/4146)
- Books
  - [Bayesian Ideas and Data Analysis An Introduction for Scientists and Statisticians](http://blogs.oregonstate.edu/bida/)


## Load packages

```{r}
library(tidyverse)
library(KMsurv)
## https://github.com/jburos/biostan
## devtools::install_github('jburos/biostan', build_vignettes=TRUE, dependencies=TRUE)
library(biostan)
```


## Load data

```{r}
data(larynx, package = "KMsurv")
larynx <- larynx %>% as_data_frame
larynx
```

```
larynx                 package:KMsurv                  R Documentation
data from Section 1.8
Description:
     The ‘larynx’ data frame has 90 rows and 5 columns.
Format:
     This data frame contains the following columns:
     stage Stage of disease (1=stage 1, 2=stage2, 3=stage 3, 4=stage 4)
     time Time to death or on-study time, months
     age Age at diagnosis of larynx cancer
     diagyr Year of diagnosis of larynx cancer
     delta Death indicator (0=alive, 1=dead)
Source:
     Klein and Moeschberger (1997) _Survival Analysis Techniques for
     Censored and truncated data_, Springer.  Kardaun Stat.
     Nederlandica 37 (1983), 103-126.
```

Here we will prepare data by creating dummy variables, standardizing continuous variables, and sorting by events then censorings.

```{r}
larynx2 <- larynx %>%
    mutate(stage2 = as.numeric(stage == 2),
           stage3 = as.numeric(stage == 3),
           stage4 = as.numeric(stage == 4),
           sage = scale(age),
           sdiagyr = scale(diagyr)) %>%
    arrange(desc(delta), time)

larynx2_covs_only <- larynx2 %>%
    select(starts_with("stage"), sage, sdiagyr) %>%
    select(-stage)

larynx2_list <- list(Nobs = sum(larynx2$delta == 1),
                     Ncen = sum(larynx2$delta == 0),
                     yobs = larynx2$time[larynx2$delta == 1],
                     ycen = larynx2$time[larynx2$delta == 0],
                     M_bg = 5,
                     Xobs_bg = as.matrix(larynx2_covs_only[larynx2$delta == 1,]),
                     Xcen_bg = as.matrix(larynx2_covs_only[larynx2$delta == 0,]))
```


## Load Stan model

```{r}
stan_lognormal_survival_model_file <- "./bayesianideas_lognormal.stan"
biostan::print_stan_file(stan_lognormal_survival_model_file)
```


## Fit Stan model

```{r, cache = TRUE}
stan_lognormal_survival_model_fit <-
    rstan::stan(file = stan_lognormal_survival_model_file,
                data = larynx2_list,
                chains = 1,
                cores = 1,
                init_r = 5,
                verbose = TRUE)
```
--------------------
- Top Page: http://rpubs.com/kaz_yos/
- Github: https://github.com/kaz-yos
