---
title: "Piecewise constant hazard Cox model in Stan"
author: "Kazuki Yoshida"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: html_document
---

```{r, message = FALSE, tidy = FALSE, echo = F}
## knitr configuration: http://yihui.name/knitr/options#chunk_options
library(knitr)
showMessage <- FALSE
showWarning <- TRUE
set_alias(w = "fig.width", h = "fig.height", res = "results")
opts_chunk$set(comment = "##", error= TRUE, warning = showWarning, message = showMessage,
               tidy = FALSE, cache = FALSE, echo = TRUE,
               fig.width = 7, fig.height = 7, dev.args = list(family = "sans"))
## for rgl
## knit_hooks$set(rgl = hook_rgl, webgl = hook_webgl)
## for animation
opts_knit$set(animation.fun = hook_ffmpeg_html)
## R configuration
options(width = 116, scipen = 5)
## Record start time
start_time <- Sys.time()
## Configure parallelization
## Parallel backend for foreach (also loads foreach and parallel; includes doMC)
library(doParallel)
## Reproducible parallelization
library(doRNG)
## Detect core count (Do not use on clusters)
n_cores <- parallel::detectCores()
## Used by parallel::mclapply() as default
options(mc.cores = n_cores)
## Used by doParallel as default
options(cores = n_cores)
## Register doParallel as the parallel backend for foreach
## http://stackoverflow.com/questions/28989855/the-difference-between-domc-and-doparallel-in-r
doParallel::registerDoParallel(cores = n_cores)
```

## References

## Load packages

```{r}
library(tidyverse)
library(survival)
library(rstan)
set.seed(13960043)
```

### Load and prepare dataset

```
aml                  package:survival                  R Documentation
Acute Myelogenous Leukemia survival data
Description:
     Survival in patients with Acute Myelogenous Leukemia.  The
     question at the time was whether the standard course of
     chemotherapy should be extended ('maintainance') for additional
     cycles.
Usage:
     aml
     leukemia
Format:
       time:    survival or censoring time
       status:  censoring status
       x:       maintenance chemotherapy given? (factor)
Source:
     Rupert G. Miller (1997), _Survival Analysis_.  John Wiley & Sons.
     ISBN: 0-471-25218-2.
```

```{r}
data(leukemia, package = "survival")
leukemia <- as_tibble(leukemia) %>%
    mutate(id = seq_len(n())) %>%
    select(id, everything())
leukemia
```

Check distribution of event times
```{r}
leukemia_summary <- leukemia %>%
    filter(status == 1) %>%
    summarize(n = n(),
              mean_time = mean(time),
              quantiles = list(quantile(time, probs = seq(from = 0, to = 1, by = 0.2)))) %>%
    unnest()
leukemia_summary
```

## Frequentist fit as a references
```{r}
coxph1 <- coxph(formula = Surv(time, status) ~ as.integer(x == "Maintained"),
                data    = leukemia,
                ties    = c("efron","breslow","exact")[1])
summary(coxph1)
```

## Model fitting
```{r}
## Load and compile
piecewise_ph_model <- rstan::stan_model("./bayesianideas_piecewise2.stan")
piecewise_ph_model
```
### Time cutoffs at 20% quantiles
```{r}
## Cutpoints
cutpoints_20 <- as.numeric(leukemia_summary$quantiles)
## First cutpoint should be time 0.
cutpoints_20[1] <- 0
## Last cutpoint should be larger than the maximum failure time.
cutpoints_20[length(cutpoints_20)] <- cutpoints_20[length(cutpoints_20)] + 1
## Show
cutpoints_20
## Evaluation grid
grid <- seq(from = 0, to = 50, by = 1)
```
```{r,results="hide"}
piecewise_ph_sample <-
    rstan::sampling(object = piecewise_ph_model,
                    data = list(lambda1_mean = 0.01,
                                lambda1_length_w = 10^4,
                                w = 0.01,
                                lambda_star = 0.05,
                                beta_mean = 0,
                                beta_sd = 100,
                                K = length(cutpoints_20) - 1,
                                cutpoints = cutpoints_20,
                                N = length(leukemia$time),
                                cens = leukemia$status,
                                y = leukemia$time,
                                x = as.integer(leukemia$x == "Maintained"),
                                grid_size = length(grid),
                                grid = grid))
```
```{r}
print(piecewise_ph_sample, pars = c("lambda","beta","lp__"))
```
```{r}
traceplot(piecewise_ph_sample, inc_warmup = TRUE, pars = c("lambda","beta","lp__"))
traceplot(piecewise_ph_sample, inc_warmup = FALSE, pars = c("lambda","beta","lp__"))
```

### Time cutoffs at all event times
```{R}
cutpoints_all <- unique(sort(leukemia$time[leukemia$status == 1]))
cutpoints_all <- c(0, cutpoints_all, max(cutpoints_all)+1)
cutpoints_all
```
```{r,results="hide"}
piecewise_ph_all_sample <-
    sampling(object = piecewise_ph_model,
             data = list(lambda1_mean = 0.01,
                         lambda1_length_w = 10^4,
                         w = 0.01,
                         lambda_star = 0.05,
                         beta_mean = 0,
                         beta_sd = 100,
                         K = length(cutpoints_all) - 1,
                         cutpoints = cutpoints_all,
                         N = length(leukemia$time),
                         cens = leukemia$status,
                         y = leukemia$time,
                         x = as.integer(leukemia$x == "Maintained"),
                         grid_size = length(grid),
                         grid = grid))
```
```{r}
print(piecewise_ph_all_sample, pars = c("lambda","beta","lp__"))
```
```{r}
traceplot(piecewise_ph_all_sample, inc_warmup = TRUE, pars = c("lambda","beta","lp__"))
traceplot(piecewise_ph_all_sample, inc_warmup = FALSE, pars = c("lambda","beta","lp__"))
```
--------------------
- Top Page: http://rpubs.com/kaz_yos/
- Github: https://github.com/kaz-yos

```{r}
print(sessionInfo())
## Record execution time and multicore use
end_time <- Sys.time()
diff_time <- difftime(end_time, start_time, units = "auto")
cat("Started  ", as.character(start_time), "\n",
    "Finished ", as.character(end_time), "\n",
    "Time difference of ", diff_time, " ", attr(diff_time, "units"), "\n",
    "Used ", foreach::getDoParWorkers(), " cores\n",
    "Used ", foreach::getDoParName(), " as backend\n",
    sep = "")
```
