---
title: "Estimating Joint Models for Longitudinal and Time-to-Event Data with rstanarm"
author: "Kazuki Yoshida"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: html_document
---

```{r, message = FALSE, tidy = FALSE, echo = F}
## knitr configuration: http://yihui.name/knitr/options#chunk_options
library(knitr)
showMessage <- FALSE
showWarning <- TRUE
set_alias(w = "fig.width", h = "fig.height", res = "results")
opts_chunk$set(comment = "##", error= TRUE, warning = showWarning, message = showMessage,
               tidy = FALSE, cache = F, echo = T,
               fig.width = 7, fig.height = 7, dev.args = list(family = "sans"))
## for rgl
## knit_hooks$set(rgl = hook_rgl, webgl = hook_webgl)
## for animation
opts_knit$set(animation.fun = hook_ffmpeg_html)

## R configuration
options(width = 116, scipen = 5)
```

## References
- http://mc-stan.org/rstanarm/articles/jm.html


## Load packages

```{r}
library(tidyverse)
library(rstanarm)
```


## Load datasets

```{r}
## multiple-row per patient longitudinal biomarker information
data(pbcLong, package = "survival")
pbcLong <- as_data_frame(pbcLong)
pbcLong
## single-row per patient survival information
data(pbcSurv, package = "survival")
pbcSurv <- as_data_frame(pbcSurv)
pbcSurv
```


## Univariate joint model (current value association structure)

```{r, cache = TRUE}
mod1 <- stan_jm(
    ## Longitudinal submodel
    formulaLong = logBili ~ sex + trt + year + (year | id),
    dataLong = pbcLong,
    ## Event submodel
    formulaEvent = survival::Surv(futimeYears, death) ~ sex + trt,
    dataEvent = pbcSurv,
    ## Name of the variable in ‘dataLong’ which represents time.
    time_var = "year",
    ## MCMC specifications
    chains = 1, refresh = 2000, seed = 12345)
```

### Priors

```{r}
prior_summary(mod1)
print(mod1)
summary(mod1)
```

```{r, h = 15, w = 7}
plot(mod1)
```

--------------------
- Top Page: http://rpubs.com/kaz_yos/
- Github: https://github.com/kaz-yos
